apiVersion: v1
kind: Service
metadata:
  name: review-service
spec:
  ports:
    - name: tomcat
      nodePort: 30719
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: grpc
      nodePort: 30562
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: reviewservice
  type: NodePort